### ISSUE TITLE
Implement Splunk!

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#1503]
Once we figure out what we have to implement per #1461, we'll add content here.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by cthulhuplus** [comment]
Document on setting up an AWS account/environment for onboarding to Splunk:
https://drive.google.com/drive/folders/1J-o00B5CBMF0H2SS68ZCiuA3B4gp59Pm

I've run into issues with LogGroups. There are supposed to be LogGroups set up for base Linux logs, which are not setup. In order to get them created, I will need to edit our Instances CloudWatch Agent configuration.

**Comment by cthulhuplus** [comment]
Converted this Issue to an Epic, will be creating additional Issues under this Epic, starting with, but not limited to:
Creating LogGroups for basic Linux logs (which is blocked by the following)
Update CloudWatch Agent to ingest basic Linux logs

**Comment by cthulhuplus** [comment]
Created https://jiraent.cms.gov/browse/CLDSUPSD-19003 to facilitate Splunk Onboarding

**Comment by cthulhuplus** [comment]
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/730bf7e0-c5a6-4cc4-9cac-198877ee5d03)

**Comment by cthulhuplus** [comment]
@NAretakis Splunk team says that our job code AWS_HIC_EAPD_SPLUNK is not in LDAP and needs to be added in order for me to log into Splunk.

**Comment by cthulhuplus** [comment]
Tested Splunk access this morning, still unable to log in with my EUAID and password.
