### ISSUE TITLE
Metrics - Research metrics

### ISSUE THREAD

**Issue by nicholeweems** [CMSgov/eAPD#2138]
Divide the Tooling, Measurements, and Dashboards document into four quadrants: Release Operational, Release Business, Post-Release Operational, Post-Release Business. Use these metrics to determine the best way to store and use these metrics.

### This task is done when...
 - [x] There is a mural board with all of the metrics in one of four quadrants
 - [x] There are methods of storage picked for all of the Release metrics

**Comment by jeromeleecms** [comment]
Will need @pphillips-fearless @radavis to discuss this as well. Add @nicholeweems for feedback too!

**Comment by mgwalker** [comment]
### Time from creation to submission/export event
- We do capture the time an APD is created. It's in the `apds.created_at` column in the database. This one is 100% backend and there's no frontend component to this metric.
- We can only reliably capture when the user presses the "Export" button; however, that does not mean they actually exported it.
   - Are we okay not having certainty about when they actually export the APD?
   - If the same APD is "exported" multiple times, do we overwrite the previous export timestamp and replace it with the newer one?
   - As it stands, any automatic metric for export would have to be collected on the frontend. The backend is not involved in the current export process at all.
   - We can capture the browser's `print` event, which is how we recommend users export the APD for now. However, the user could be printing a section to review rather than printing/exporting the whole APD (as Caryn pointed out recently). I would caution against using the `print` event.
- We would need a new API endpoint to capture the export event, and a new field in the data model to capture the export timestamp - perhaps in the `apds` table. The time spent would be the duration between the creation date and the export timestamp and could be calculated at runtime rather than stored.

### Date/time of each session; time spent per session
- We need to define what a session is.
   - Is it from the time the user logs in until they log out? We could measure this one entirely on the backend.
   - Is it from the time the user opens the app until they close it? This one would likely need to be a combination of frontend and backend. The browser events for when a window/tab closes are finicky, so we may not be able to reliably collect that. As a backstop, the backend could declare a session "over" if the user hasn't hit the API for some length of time. (Maybe a couple of hours?) The downside to this approach is that we can't be sure when the user actually ended their session. We would also need to research what happens when a computer goes to sleep, etc. - if a user left the app open overnight, should it be considered one very long session, or should we assume that they began a new session in the morning?
   - Is it something else?
- How much detail do we need? Do we need to know this information per user, or anonymized across all users?
- This would might require new API endpoints to post session events, and definitely requires changes to the data model. We might be able to latch on to the `auth_sessions` table if we need per-user data. Otherwise, probably want a new table.
- This also adds state to the API, which is (essentially) stateless at the moment.

### Time spent in each section
- How granular should this be? Do we want to know how long they spend on each page, or how long they spend in each textbox? The latter is considerably more complex but maybe provides more valuable data.
   - Tracking time on pages shouldn't be *too* hard. I think we would only need to track when a user landed on a page, and then we could figure out the duration they were there based on either the end of their session or they navigate to a different page.
   - Tracking time in individual fields is a bigger undertaking because we would need to hook into the `focus` and `blur` events of every form element. We would need to investigate how we might put a wrapper over the design system's form elements to provide that for us.
- This isn't tracked at all, so we'd need API endpoints for posting the information plus data model changes to capture it all.
- This requires state in the API as well, though it could be the same state that was created to support session times.

### Export events
- Not entirely sure what we are supposed to capture here. Is this a list of all the times an APD was exported?

### For everything
Are we looking for aggregate statistics? That is, do we want to capture these statistics on a per-user, per-APD, per-state, or other granular level, or do we want to just keep updating one set of aggregate data?

@pphillips-fearless @radavis Curious if my message resonates with y'all at all. Most of this would be entirely new, so I'm kind of approaching it as greenfield, in a sense: what are the gotchas that are always true, and how do we want to approach those. Then we can start to figure out and detangle the gotchas that are specific to this app.

**Comment by jeromeleecms** [comment]
@pphillips-fearless Will check in with @mgwalker about next steps on this. Will either close this or move to next sprint.

**Comment by pphillips-fearless** [comment]
@jeromeleecms, @mgwalker, @nicholeweems, @radavis I put some thought into what the next steps should be, based on my memory of our meeting on April 20.  I remember during that meeting that we discussed Greg's questions from the comment above.  First, I have two recommendations (points to decide):

1) Recommend that capture raw events rather than making any type of interpretation and computing deltas between them.  That way we let those analyzing the data decide, for example, whether to define "APD creation time" as the time starting from first creation and ending at export, or first print, or last print

2) Recommend to capture multiple data points and don't overwrite earlier data.  Again, save all the raw data.  Then you can do an analysis, for example, if a user exports and prints multiple times to figure out what really happened and what the trends are

If we agree to those recommendations, then we need tasks to capture the following data points (grouped by KPI):

-Time from creation to Submission/Export
    1) time APD is created - done
    2) time export button is pressed (captured on front end and sent to API)
    3) time of each print event (captured on front end and sent to API)
-Date / time of each session
    1) time of each login (backend)
    2) time of each logout (backend)
    3) time each page is opened (captured on front end and sent to API)
    4) time browser window/tab is closed (captured on front end and sent to API)
-Time spent per session
    see above
-Time spent in each section
    1) time in each textbox (this will generate a large amount of data and its usefulness may not be worth the storage maintenance cost)
-Export events
    see above

I also think an initial database design task to set up the table(s) to store the data and (probably a separate task to) set up API endpoint(s) to receive data from the client.

I'm sure I overlooked something, so we can meet again or discuss here or in slack.

**Comment by jeromeleecms** [comment]
Can we schedule some time to talk through this? Since this the first of related issues, it would be good to see if any of this content flows into the other tooling items.

**Comment by nicholeweems** [comment]
Sure, meeting has been scheduled.

**Comment by pphillips-fearless** [comment]
At our meeting today we approved the approach of collecting raw data as described above, with a long-term desire to create ways (eg, queries, reports, aggregates) to turn the raw data into useful information.  The next steps are to create tasks for database table(s) design, API endpoint, and front-end data point capture.  we'll put the existing tooling and measurement tasks in the fridge for now.

**Comment by thetif** [comment]
Based on the operational metrics needed, we will try to store those in Google Analytics. The current APD structure will satisfy all of the business metrics needed for release, except for export events. These will be stored in an APD events database table that will also be needed for other business events post-release. We will also be trying to use react-tracking in conjunction with Google Analytics and the database to track events.
