### ISSUE TITLE
Inline Instant Error Validation

### ISSUE THREAD

**Issue by jjames521** [CMSgov/eAPD#2346]
Split from #2092

This holds all the fields that need to be added/or added back in for validation.

Cross reference for any of these visually here (this mural includes things that will not be featured in this ticket) 

https://app.mural.co/t/cmsmural6360/m/eapd5455/1588781600846/74a95a2db5d0b3e72c73cc7a96e6b501f40dcbd1

**Mockup:**. (How error text would fall, underneath the field.)

![Screen Shot 2020-07-15 at 5.27.25 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/47856b38-da9d-47a2-9c01-046df7731bdd)

These fields include:

**Does this person have costs directly attributable to this program**
If yes
Costs with benefits (Please provide a cost greater than or equal to $0) Note (Number equal to 0 is OK because they may have a cost in  future FFY only)

FTE Allocation (Please provide a number greater than or equal to 0.0001)

**_Program Activities-Objectives and Key Results_**
**Activity Schedule** 
Planned Start Date (Please Provide a start Date) (Feature of this consideration: Planned end date can not be before start date)
**Exception** Planned end date (ok to be blank (if ongoing activity)) (Doesn't require an end date)

**Milestones**
Planned Start Date (Please Provide a start Date)
**Exception** Planned end date (ok to be blank (if ongoing activity)) (Doesn't require an end date)

_**Program Activities-State Cost Categories**_
**Personnel Section**
Costs with benefits (Please provide a FTE cost greater than $0). (System errors out field and changes back to zero with error message if a negative number is provided)

Number of FTEs (Please provide a FTE number greater than 0.001)

**Non-Personnel Cost Section**
2020 cost (Please provide a cost greater than $0.  Use whole numbers cents will be rounded to the closest whole dollar value)

_**Program Activities-Private Contractor Costs**_
**Private contractor costs section**
Contract term
Start (Please provide a start date)
End (Please provide an end date)
Total contract cost (Please provide a contract cost greater than $0)

**This is the hourly resource section**
_If not hourly resource_
FFY 2020 Cost (Please provide a dollar value in this field) (Extra description: Cost $ >=0)
FFY 2021 Cost (Same as above)

_If hourly resource_
FFY 2020 and 2021 fields
Number of hours (Please provide a number greater than or equal to 0 in this field)
Hourly rate (Please provide a dollar value greater than 0)

_**Program Activities-FFP and Budget**_
Other funding amount (Please provide an other funding amount greater than or equal to $0)
Estimate Quarterly Expenditure **(Table)** (extra description: see mockup below on table errors) (Please update the quarterly percentages so the Subtotal does not exceed 100%)

![TableErrorValidation.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/6c6ed9d0-3112-4171-bf6c-32bfb0c96f11)

Error text would be under table in any table fields with errors

_**Proposed Budget**_
Estimated Quarterly Incentive Payments **(Table)** (Follow guide from previous mock) (Please provide a number greater than or equal to $) (Please use only whole numbers when providing counts)

_**Choose the federal fiscal year(s) this APD covers.**_
(At least one FFY must be selected to continue with your APD. Select your FFY(s).)
This becomes a page level validation, the user cannot leave the page without selecting. 
Will need to remove the other errors in the system from the previous bandaid. 
Use modal pattern for page level validations when we don't want them to leave the page. 

### This task is done when...
 - [ ] Validation added into appropriate fields upon blur
 - [ ] Product and Dev agree that the fields/validation is correct.

**Comment by jeromeleecms** [comment]
Need to discuss this with Design now that this is being bumped in the roadmap.

**Comment by beparticular** [comment]
Note - do not change and of the field titles or case if they don't match to staging, it may just be a typo. This is just to show where the field lives, and what the validation error should be. 

|Page|Field|Content|Consideration|
|---|---|---|---|
|Key Personnel > Add KP > Does this person have costs directly attributable to this program > Yes|Costs with benefits|Provide a cost greater than or equal to $0|Number equal to 0 is OK because they may have a cost in future FFY only|
|Key Personnel > Add KP Does this person have costs directly attributable to this program > Yes | FTE Allocation|Provide a number greater than or equal to 0.0001|
|Activities> Activity Overview > Activity Schedule|Start Date|Provide a start date.|Feature of this consideration: Planned end date can not be before start date, no end date is required|
|Activities> Outcomes and Milestones|Start Date|Provide a start date.|no  end date is required|
|Activities > State Staff and Expenses > Add state staff|Cost with benefits|Provide a FTE cost greater than $0|System currently errors out field and changes back to zero with error message if a negative number is provided|
|Activities > State Staff and Expenses > Add state staff|Number of FTEs|Provide a FTE number greater than 0.001||
|Private Contractor Costs > Add contractor > Full Contract Term|Contract start date|Provide a start date.||
|Private Contractor Costs > Add contractor > Full Contract Term|Contract end date|Provide an end date.||
|Private Contractor Costs > Add contractor|Total contract cost|Provide a contract cost greater than $0.||
|Private Contractor Costs > Add contractor|FFY XXXX Cost|Provide a cost greater than $0. Use whole numbers, cents will be rounded to the closest whole dollar value.||
|Private Contractor Costs > Add contractor > This is an hourly resource > No|FFY XXXX Cost|Provide a dollar value greater than 0.||
|Private Contractor Costs > Add contractor > This is an hourly resource > Yes|Number of hours|Provide a number greater than or equal to 0 in this field.||
|Private Contractor Costs > Add contractor > This is an hourly resource > Yes|Hourly rate|Provide a dollar value greater than 0.||
|Cost Allocation and Other Funding|Other funding amount |Please provide an other funding amount greater than or equal to $0|---|
|APD Overview|FFY|At least one FFY must be selected to continue with your APD. Select your FFY(s).|This becomes a page level validation, the user cannot leave the page without selecting. Will need to remove the other errors in the system from the previous bandaid. Use modal pattern for page level validations when we don't want them to leave the page.|
|Proposed Budget|Estimated Quarterly Incentive Payments Table|Provide a number greater than or equal to $. Use only whole numbers when providing counts|Location: Error text would be under table in any table fields with errors. See screenshot below|
|Budget and FFP|Estimated Quarterly Expenditure Table| The quarterly percentages Subtotal should not exceed 100%|Location: Error text would be under table in any table fields with errors (see screenshot below)|

![TableErrorValidation.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/6c6ed9d0-3112-4171-bf6c-32bfb0c96f11)

**Comment by jeromeleecms** [comment]
All dev tickets have been created. Tif will take what else she needs from this once we start working on this.
