### ISSUE TITLE
Review/change Activity Overview section for better content flow

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2372]
The Activity Overview page contains several key components that are not included in the nav bar since the team has decided not to add another layer to the nav bar. 

Original solution - The title should be updated to provide users a better way to find the contents of this section
Current idea - Consider the activity overview page and outcomes and milestones sections together and determine what should live together, what new pages need to exist, etc. (Changing the title to reflect this)

Starting point for Sprint ending 3/5 - take screenshots of each component and add to the MES Expansion Mural Board so we can move them around and find the right homes for all fields/components. 

Will do the work collaboratively in next Sprint - in progress, getting ready for inclusion in a prototype
Consider breaking out Milestones from Outcomes and metrics as part of this as well as #2168

### This task is done when...
 - [x] Suggestions for a better title and/or flow have been provided
 - [x] Team has agreed on a new flow/designs for testing 
 - [x] Determine what needs to be changed for HITECH vs MES

**Comment by CSwartzHMA** [comment]
@beparticular @jeromeleecms After some thought on this, here are a couple of options:

1. Overview, Alternatives, Standards and Conditions
2. General Description: Details, Alternative Considerations, Standards and Conditions

These are both long and I am not sure how they would look, but include details that would allow users to find key sections of the APD.  Alternatively, consider moving Alternative Considerations and Standards and Conditions to a separate page.

**Comment by beparticular** [comment]
@CSwartzHMA  This page actually needs a lot of refinement to make sense (headers aren't consistent, sections run together with no separate, etc), and it does seem like some of these would be better suited to their own page. I'm going to sleep on it and look again fresh tomorrow.

**Comment by beparticular** [comment]
This will be a bigger part of the structure conversation. #1823 related

**Comment by beparticular** [comment]
Consider breaking out Milestones from Outcomes and metrics as part of this

**Comment by akuas** [comment]
[Activity Overview Designs](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2522%3A0)

**Comment by akuas** [comment]
Hi @NAretakis can you please review the Activity Overview designs. I haven't edited it since last week's design sync but I wanted to know if I have the go ahead from product.

**Comment by NAretakis** [comment]
@akuas  Activity Overview designs are good. The only thing that stands out as slightly odd is the "compliance to federal regulations" header/box. Since I was just looking at the conditions of enhanced funding section, I am wondering if this is actually redundant because we have the conditions of enhanced funding section (which are the federal regulations the activity needs to comply with). 

The only thing this section does is include a sort of attestation that the activity will comply with all applicable federal regulations, but I think we might be able to actually make sure that is covered in the conditions of enhanced funding section.

All that said, I think we can go forward, and then do some testing to see if this actually is redundant with any other sections in the app.

**Comment by akuas** [comment]
I see, maybe it's a matter of rewording that field but the Compliance to Federal Regulations, as I understand it is users' opportunity to explain how its allowable to under federal regulations. Its a more general/high-level question for instance your medicaid director might suggest this activity or it is in line with Medicaid efforts to create reusable open source systems. But I understand your concern, if users interpret in the same way as Conditions for Enhanced Funding, the field will result in erroneous and redundant responses. This would be something interesting to test out.

**Comment by beparticular** [comment]
This is ready to go forward for the prototype. 

This issue is done as far as design goes. It will be tested the week of April 19. If there are any additional changes after testing, this issue can be re-opened as needed to help with continuity of the design and to hand off final designs to dev in one issue.
