### ISSUE TITLE
Rename State Cost Category page and update Nav Bar to better assist users in navigation

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2390]
Nav bar and title for State Cost Category page do not currently guide users from other pages back to where data was entered if changes are needed later in the data entry process.

### This task is done when...
 - [x] Team has agreed on what this page should be titled
 - [x] Change log has been created

**Comment by CSwartzHMA** [comment]
Team discussion today included a reference to the tables which use the term "In House Costs" as a collective description when state staff costs and other state expenses are combined. One possible way to bridge this concept is to rename the "State Cost Categories" page to "In-House Costs (State Staff + Other State Expenses)".

**Comment by beparticular** [comment]
@CSwartzHMA I was thinking back to our debrief yesterday and our thoughts around simplifying some of the nav labels (like Activity Schedule Summary = Activity Schedule). Why is this label "State Cost Categories" instead of "State Costs"? Categories is a reference to a column in a table on the template, not the title of a section. 

Also, I was looking back at the template and the only place that "in-house" is used, is on that Quarterly table, so it doesn't seem like it's an important enough term to be added to the nav, if it's not used on the State Cost page except in help text. To me it seems like the better move here would be to make the table consistent with the navigation and State Costs page. 

cc @jeromeleecms thoughts?

**Comment by jeromeleecms** [comment]
State costs: I would want to explore "State Personnel and Expenses" (or some derivative of it). We wanted to rename the nav content so people knew what to expect in that section. I'm OK with avoiding the word "in-house" since we include the context in much of the help text and it only appears in the final table to align with what is in MBES.

Activity Schedule Summary: Not too opinionated on this, if have better words to describe this. I'm OK with it as is or "Activities Schedule" is also OK.

Open to simplification -- but let's also start thinking through how much content polishing we want to do. If it's clearly wrong, let's fix that -- if we start wandering down the path of perfection, we'll never finish :)

**Comment by beparticular** [comment]
@jeromeleecms @CSwartzHMA 

![Statestaff.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/a37397e4-309e-49db-a6aa-d5bc10b5aacd)

**Comment by jeromeleecms** [comment]
If we are aiming for consistency, should we label this as "State staff and other expenses" or "State staff and other state expenses" ? Though it's a longer label, this would be most consistent with how we refer to it within the application. But the spirit of the approach is fine.

**Comment by beparticular** [comment]
I don't think it's important to be exactly consistent, but to get the gist across using the same terms. 
I don't think "other" is descriptive or proprietary enough to make a difference in the navigation. 

I was looking for feedback on the the table label more than anything? Does this accomplish what we need to both show the user where to get back to the in the app and to let them know this is where this in-house cost lives?

**Comment by CSwartzHMA** [comment]
My only thought is that it might help to switch the label in the table to In House Cost (State staff and expenses) keeping the table consistent with the MDBTs, but I could go either way with that. Otherwise, I think this will work and we can see if it seems smoother in the next round of user research.

**Comment by jeromeleecms** [comment]
Sounds good - I'm fine with how Jenn proposed this and per Caryn's suggestion we can just put this in front of people in our next round of research.

**Comment by beparticular** [comment]
State needs: medicaid detail budget table, and quarterly reports to show they did their funding appropriately, a related federal form rolls up costs into all state costs = in-house costs. 
The in-house costs line in the table shows this roll up of state staff and other state expenses. 

Federal use: will use info to import (copy/paste) to mastertables. 

Per convo with Caryn, let's go with what's in the mock up for now and keep an eye on this as a potential issue.

**Comment by beparticular** [comment]
@thetif this is ready for dev 

Change log - 

- Change nav label to State staff and expenses (from State cost categories) 
- Change page header to State staff and expenses (from State cost categories) 
- Change the FFP and Budget > Estimated Quarterly budget table first row to 
State Staff and Expenses 
(In-house Costs)    (would be ideal for this to be on its own line for clarity) 

![Statestaff.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/a37397e4-309e-49db-a6aa-d5bc10b5aacd)

- Make sure the export view reflects the recent changes to the headers: 
Change "In-House Cost Categories: State Personnel" to 
Correct "State staff"

Change "In-House Cost Categories: Non-Personnel" to 
Correct "Other state expenses" 

![Screen Shot 2020-07-24 at 3.38.27 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/ec4809a1-aa2e-4785-874c-ccde7c7fef57)
