### ISSUE TITLE
Conduct Dev Ops Contingency Plan Execution Table Top Exercise

### ISSUE THREAD

**Issue by nicholeweems** [CMSgov/eAPD#2529]
In order to harden the existing [DevOps Contingency Plan](https://docs.google.com/document/d/1Zv9ctPWvi_UfXoBDJ0h1RrPwv771kP_Ri8Q1v-bVGyg/edit?usp=sharing), key personnel plans to execute the plan via a table top exercise

### This task is done when...
 - [x] The table top exercise is completed
 - [x] The Dev Ops Contingency Plan is updated to account for new found information and experience as a result of completing the table top exercise
 - [x] Dev Ops Lead and all other key personnel confirm the Dev Ops Contingency Plan meets the current team need

**Comment by cthulhuplus** [comment]
@thetif @radavis @tbolt 
In order to do this activity I will need you to check and make sure you have the ability to create an SSH key in AWS. If you need to create a ticket to get AWS access you can follow this template:

https://jiraent.cms.gov/browse/CLDSUPSD-5881

Once in AWS you go to "Services" > "Compute" > "EC2" > "Network & Security" > "Key Pairs" > "Create Key Pair"

Once you've created your key pair let me know and we can test your access.

**Comment by radavis** [comment]
I get a fun error when attempting to create or import a SSH key...

Please advise.

![Screen Shot 2020-10-02 at 4.18.50 PM.png](https://images.zenhubusercontent.com/5e62a052e57324bfda300f92/69cd18e7-58d0-4111-8a08-bcd7ac735a63)

**Comment by cthulhuplus** [comment]
^^^
Please create a new Jira ticket and request the ability to create an SSH key. I couldn't find an example, but I'd present them with the error you are getting and the method that you are using to create the SSH key.
