### ISSUE TITLE
Conduct Disaster Recovery Table Top Exercise

### ISSUE THREAD

**Issue by nicholeweems** [CMSgov/eAPD#2530]
In preparation for going live, conduct a full scale table top exercise of varying disasters/outages randomly organized by the Master of Distribution (Bill Brooks).

This task is done when...
  - [x] The table top exercise is completed
  - [x] All plans/documents including internal and external comms are updated to account for new found information and experience as a result of completing the table top exercise
 - [x]  Dev Ops Lead and all other key personnel confirm all plans meets the current production need

**Comment by cthulhuplus** [comment]
Pulling this up based on a conversation with Jerome.

[11:50 AM] Hello everyone! We have an upcoming tabletop test for the MACPRO suite of applications. This is an annual requirement and as part of the major consolidation we’ve been doing over the last year or so, eAPD and SPoTT will need to be included. What I will need from each of you:
List of personnel that you would like to include in the test. This should be limited to leads from within your groups that can cover topics such as how do we restore eAPD/SPoTT if something were to disrupt standard operations.
Someone will need to jot down notes of specific actions that are taking place as we go through these hypothetical scenarios. What I usually do is just read each of the scenario cards, then let the group take over from there while taking notes of what transpired.
Last year’s assessment involved personnel being unavailable due to food poisoning, so we went over how their duties are still performed without them being available. It then lead to an incident occurring in our next scenario. These “sick” people were still unavailable and we had to envision how we would handle such an incident without their availability. Expect something similar this year hint hint
As we have several groups involved going through the same scenario, our results will likely be the same on what we do to restore services. Send me your notes when they’re done and we’ll sit down on a call afterwards to consolidate our actions into one document for John’s signature and approval.
I’m looking to have this scheduled for Wednesday, February 10th from 12:00 - 1:00. Please make sure you and your team are available. This is a mandatory requirement.
The first ~15 minutes involve training. Doing this hits a few additional requirements for us related to contingency planning and incident response.
Please let me know if either of you have any questions or concerns about what exactly this is and what we’ll be doing.
[11:50 AM] Can you look at these bullets and tackle? Let me know if anything looks wonkadoo?

**Comment by cthulhuplus** [comment]
List of personnel that you would like to include in the test.
- Tif or Richard (Application SME) (or both)
- Bill Brooks (Infrastructure/Deployment SME)

**Comment by cthulhuplus** [comment]
Incident Response Plan
https://docs.google.com/document/d/1QapId11-ItcL_92b7eYU1z-E-BPj7Yq0GlbF7UTf5oc/edit?usp=sharing

Infrastructure Contingency Plan
https://docs.google.com/document/d/1W-hx-AIvW-LHG9nC979vApLrW5_kNF58EHwrN8dsUKA/edit?usp=sharing

Database Recovery Plan
https://docs.google.com/document/d/1xrxiD7Lj9rjBs4HCb1ecIew_BJUD_k_vqbaQVZP-pKw/edit

On-Call Policy
https://docs.google.com/document/d/1Xj0OAvggbrYCk5Ax9dngKPy6kBkA5JgBxoFCmY_d9ng/edit?usp=sharing
