### ISSUE TITLE
Create form for user to request additional states

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2582]
Add an item to the dropdown menu that allows the user to request access to additional states. They should not have the ability to request access to a state they already have access to or remove access to a state they already have access to.

![Screen Shot 2020-10-13 at 1.18.34 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/8842c906-e951-44ff-b686-dbac43ee2cbc)

![Screen Shot 2020-10-13 at 1.18.45 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/9bd50ac1-aff7-4840-8363-ed0d729cb9e7)

### This task is done when...
 - [ ] the user can click the Manage account item in the dropdown
 - [ ] clicking Manage account takes the user to the request access form

**Comment by thetif** [comment]
@beparticular is this still how we want to do this? Can a user manage (aka remove) their own affiliations?

**Comment by tbolt** [comment]
@beparticular had a few questions on this. here is where im at so far-
![image.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/19ff2221-6e94-4325-9c9b-faf2e5f94a13)

1. I haven't spent too much time trying to match the design. I was trying to put it into the card-style layout we have but it was being a pain. Is that preferred? Currently I just have everything left-aligned. 
2. What is the Author label from the original design?
3. Currently I have the users affiliations listed separate from the ones they are requesting access to . This is a fixed list that they can't modify (the badges are grey and the button is disabled). This will show ANY affiliation they have. Which includes Requests for access, revoked / denied, and approved affiliations. I'm not sure how we want to handle those cases. Open to ideas
4. What happens when they hit save here? It could go to the "Thank you we will verify..." page (below) or reload the page to show the updated "Current affiliations" list. 
5. Are there any plans to add more to this Manage Account page?
![image.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/02f11dad-7999-4a45-a121-4872e25c54b4)

**Comment by beparticular** [comment]
@tbolt 

1. I'd just match it to the design system or whatever we did in selecting the state affiliations initially. 
2. I think that was left over from when a user might possibly have two roles, but I don't think that's relevant at this moment. 
3. Let's chat
4. Let's chat
5. Not at this time, but could be in the future as roles and multi users are introduced

**Comment by tbolt** [comment]
Documenting a quick update/question based on team conversations-
* In order to make it easier to understand why certain states would not appear in the Select Affiliation field, I made the component show existing affiliations. This presents a new problem though since it will show ALL affiliations including Requests, Revoked, Denied, and Active ones.

**Comment by beparticular** [comment]
#3160 @tbolt I added a new design ticket to represent the work around making the decisions for the full functionality of the multi-state select. Hope to talk it through at design sync this week.
