### ISSUE TITLE
Back to eAPD link at the top of the print preview page is missing

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2712]
During a Beta Testing debrief, we discovered that the "< Back to eAPD link" at the top of the print preview page has gone missing.

This was described in #2117 and implemented in #2182.

We should put the link back to people can navigate back to their APD without having to go to the dashboard first.

### This task is done when...
 - [ ] Back to APD link has been restored to the top of the export page
 - [ ] Code has been reviewed by someone else
- [ ] Design signs off
- [ ] Product signs off
- [ ] Root cause and other potential issues have been identified

**Comment by tbolt** [comment]
Regarding the root cause and other potential issues:
The **Back to APD** link was rendering in the document but was hidden behind the nav bar. We had `id=start-main-content` on an `H1` in the page instead of how we typically have it on the `<main>` component. Moving that ID to the `<main>` component applied the necessary css style to move the content down below the nav. We may want to do a more thorough review of our css layout architecture as there may be more inconsistencies like this one. These can easily compound over time and introduce more regressions.

**Comment by beparticular** [comment]
I'd very much like to do a review of our css layout architecture. Maybe this falls into the tech debt timelines? @tbolt @thetif

**Comment by jeromeleecms** [comment]
@tbolt @beparticular Can one of you spin up an issue describing the specific scope of what this review would cover (at least ideally), please? This issue of the content slipping under the nav bar has happened previously (content and scrollbar for the left hand nav) so let's make sure to capture this and ensure we have a more holistic solution. 

We need to have a multisprint planning/roadmap review soon, so we can include this review request as part of a broader discussion of what our team wants to do in the tech spike.

**Comment by beparticular** [comment]
@tbolt do you want to discuss at the next design sync?
