### ISSUE TITLE
Private contractor cost page field labels are confusing to users

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2726]
Findings: Private Contractor page issues:
1) Folks are reading the Total Contract Cost to be the sum of FFY’s they’ve entered. 
2) Folks aren’t always putting the full contract term into the dates, but the term they are requesting funds for. 

Recommendations: 
Before release: Change before release as errors in this section could make the APD not approve-able. We believe making changes to the field labels vs making a change to the help text may increase understanding of this page. Further discussions need to be had to determine the exact language. 

After release: Additionally - consider the language around activities and milestones as well to be consistent

### This task is done when...
 - [x] Initial field labels and order of fields on this page are determined 
 - [ ] Field labels and order of fields on this page are agreed upon

**Comment by beparticular** [comment]
@jeromeleecms ready for review - I'd like to get these done and moved to dev tomorrow (Wednesday 12/23) 

Changes made: 
1) Contract Term = Full Contract Term
2) Added language about option years to help text
3) Start date/end date = Contract start date/end date
4) Added "is informational and" to the help text under "Total Contract Cost"

![Screen Shot 2020-12-22 at 4.34.25 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/f3eff00c-fbc7-4d3f-9dc9-c307fcdd2072)

**Comment by jeromeleecms** [comment]
1) Contract start date and Contract end date. For consistency, are we doing title casing? (Also "This is an hourly resource." it not title cased).
2) For the help text, we should be more directed when asking users for data input (other parts of this app already follow this style):  "Provide the total length of the contract, including any option years. Contract term may extend beyond the FFY(s) included in this APD."
3) For "Total Contract Cost," we also use the language "Total Not To Exceed Amount" to specifically address the this idea. Total Contract Cost for the title of the help text is fine. For the help text, what do you think of, "Provide the total not to exceed amount of the contract, including costs for the option years. This is not the amount you are requesting for the FFYs and will not be added to your FFY requests." I'm hesitant to use the word "informational" because this information IS used to make decisions on the APD and the funding associated with the contract.

Thoughts/feedback?

**Comment by beparticular** [comment]
@jeromeleecms  

1) This is the casing we use for dates. I think casing consistency is something we need to address holistically and not before release, and maybe already have a ticket out there for part of that?

2) I'm good with the language you provided here.

3) I think if states know what the "total not to exceed amount" is, that should be a more informative help text. 

In addition, let's look at why the text is wrapping differently under Total Contract Cost than it is under Full Contract Term. 

Updated screen - 
![Screen Shot 2020-12-22 at 5.28.41 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/97cd55d6-7da2-49aa-b213-9cae117cb569)

**Comment by jeromeleecms** [comment]
1. Right - I thought we already agreed to move to title casing...?  https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/2438 <-- maybe these specific items don't include dates?
2. 👍 
3. Also sounds good.
4. Also good with figuring out the weird text wrapping where possible. This appears in multiple areas of the app and is most obvious when we use plain <textarea> type tags.

**Comment by beparticular** [comment]
1. Does not include dates. I don't think this is something we should worry about before release.

Is this ok to move forward to dev? @jeromeleecms

**Comment by jeromeleecms** [comment]
That's fine. Spin up an issue for content review?

Other than that, good to go.

**Comment by beparticular** [comment]
@thetif ready for a dev ticket, last screenshot reflects the following changes made:
1) Contract Term = Full Contract Term
2) Added language in both help texts about option years to help text
3) Start date/end date = Contract start date/end date
