### ISSUE TITLE
Update assurances and compliance page with accurate links and details

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2862]
On the Assurances and Compliances page:

### This task is done when...
 - [ ] On the third question, update 45 cfr 95.615 -> 45 CFR 95.613 and change link to: 
https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=1&SID=6d93b829c0db163a0124bfeae1704e42&ty=HTML&h=L&mc=true&r=SECTION&n=se45.1.95_1613

 - [ ] On the eighth question, Update the citation to 42 CFR 433.112(b) (previously listed as 42 CFR Part 433.112(b)(5)-(9))

 - [ ] On the last question : Update Securities -> Security

**Comment by tbolt** [comment]
One thing to note with these changes:
We have a file that contains all of the regulation titles with their corresponding links. When updating them it causes the existing APDs to break slightly by keeping the previous titles and de-activating the links-
![image](https://user-images.githubusercontent.com/2279260/108382301-ac255580-71d6-11eb-827d-1e3589b14838.png)

I suppose this is by design as to keep the answers correspond to the actual question(s) asked but wanted to document it just in case we have any concerns with it.

Creating a new APD shows the updated title + links just fine though.

**Comment by beparticular** [comment]
@tbolt I think that's ok for changes now. @jeromeleecms how often do you think there would be regulation changes that might affect existing APDs, once we have folks in the system?
