### ISSUE TITLE
Explore where Outcomes and Metrics should live within an APD

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2894]
With CMS guidance around the new outcomes and metrics work, what is the best way for us to capture outcomes and metrics in the eAPD system to match the data and regulation needs of CMS?

History - the outcomes and metrics fields used to be OKRs (Objectives and Key Results) fields, and are currently housed in Activities. Is that the best way to represent the data that CMS wants to capture and the importance of O&M?

What other guidance will come from CMS on O&M? 

Related #2732

### This task is done when...
 - [ ] TBD

**Comment by NAretakis** [comment]
This issue corresponds with #2939 and may be resolved once we complete 2939.

**Comment by NAretakis** [comment]
We can now resolve this issue. Because we are confident that Outcome and Metrics will reside at the **activity level**. We are still tracking Modules/Projects, but outcomes should live at the activity level. 

The list of example activities below is what we'll ultimately use when we work on the PRA package, but we are also not limited to this list. 

_Examples of individual activities include but are not limited to: E&E online application, E&E worker portal, E&E noticing system, claims processing engine, claims processing prior authorization, claims processing record keeping, HIE interface(s), CQM databases, decision support systems analytics platform, provider enrollment screening, provider fraud/waste/abuse, managed care member enrollment, etc. For each activity described below, provide the following details in their own respective subsections._
