### ISSUE TITLE
[Dev] Create eAPD JWT

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3029]
Our current JWT middleware is too chatty, either contacting Okta or the database on every request. Once a user is authenticated the backend the server will create a JWT that contains all of the states that they have affiliations for and what the status of those affiliations is. Temporarily the JWT should also contain the user's role and activities for the first affiliation in the list.

### This task is done when...
 - [ ] the server creates a JWT with all of the user's affiliations and their statuses and the user's role and activities for the first state
 - [ ] the server uses that JWT for future requests and falls back to Okta or the database if necessary

**Comment by knollfear** [comment]
To make sure this will work and everyone is aligned I have created the following example:
many fields are ignored as they are unnecessary.  These results are for a single user:
auth_affiliations = [
	{
		state: AK,
		role: StateStaff
	},
	{
		state: MD,
		role: stateStaff
	},
	{
		state: MO,
		role: pending
	},
	{
		state: MI,
		role: stateAdmin
	}
]
state_admin_certifications = [
	{
		state: AK,
		expires: 20210911
	},
	// Expired
	{
		state:MD,
		expires: 20201212
	}	 
]

When logging in this user is assumed to be using AK as it is the "first" state.   As a result the user object looks like this:
user = {
	state:{
		id: AK
	},
	role: stateAdmin,
	activities: [some, list, of, activities, adminStuff]
}

This will allow endpoints to validate requests in basically the same way they have been with no modifications.

If at some point in time the user switches to be using MO as their state the payload will change to look like this:

user = {
		state:{
			id: MO
		},
		role: pending,
		activities: [],
	}
}
The role is not yet approved, so they will remain in a pending (or revoked if that applies) status and have an empty activity list.  This should prevent them from viewing or modifying any resources.

Finally, if they switch to MD, where they have an expired state_admin_certification they will look like this:

user = {
	state: {
		id: MD,
	}
	role:stateStaff
	activities: [list, of, things]
}
having fallen back to the role of stateStaff because their state_admin_certification has expired.  Similarly, Michigan lacks a state_admin_certification so if the user chooses Michigan they will be stateStaff and not stateAdmin.
