### ISSUE TITLE
Revisit "on-call" process/list/schedule

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3047]
Per the go-live tabletop, we wanted to revisit "on-call" process/list/schedule.

### This task is done when...
 - [x] Revisit relevant document
 - [x] Do a scenario tabletop exercise to confirm the on-call process works
 - [x] Adjust parts of the process from the tabletop if necessary.

**Comment by cthulhuplus** [comment]
https://docs.google.com/document/d/1Xj0OAvggbrYCk5Ax9dngKPy6kBkA5JgBxoFCmY_d9ng/edit?usp=sharing

**Comment by cthulhuplus** [comment]
Trying to find a time that works for everyone for the tabletop exercise

**Comment by cthulhuplus** [comment]
The topics we covered were;

1. Logs and where and how to find them
2. "On-call" rotation and when it's appropriate to follow
3. Hours of Operations/Support
4. Creating and logging Incidents, both Security and Availability
5. User communication/support, ft. a real Issue from our backlog (which Tif picked up on!)
6. Leveraging the CMS Cloud Support and Web Help Desks

The scenarios we worked through were:

1. You're having issues with your own PR (On-call no necessary, logs can be found in CloudWatch, Splunk, or on the Test Instance)
2. Prod is down! (Hours of operations, Incident report, contacting a specialist, and the process for running an off schedule deploy to Prod to patch Prod)
3. Third Party Vendor leaks our pipeline creds (Security incident, contact CMS Security Help Desk, documenting Security incidents and history)
4. User support via Email to the shared email box (Creating an Issue to address a bug/Checking for a known bug/potentially reprioritizing a known bug based on user feedback)
5. Bill is unavailable and CircleCI/Pipeline Tool is acting up (Contacting CMS Help Desk, creating an Incident since a major tool in our pipeline is unusable, manually running builds from the command line)

**Comment by NAretakis** [comment]
This looks good to me, are we ready to close this issue?
