### ISSUE TITLE
Review SLA/issue resolution with Dev and Product

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3048]
Per the go-live tabletop, we wanted to review SLA/issue resolution with dev team.

### This task is done when...
 - [x] Review relevant documentation
 - [x] Identify the support process and SLAs
 - [x] Pin the process "somewhere"
 - [x] Document rolling process of types of support questions that come in
 - [x] Document how we share feedback, track issues
 - [x] Do a scenario tabletop exercise to confirm the on-call process works
 - [x] Adjust parts of the process from the tabletop if necessary.

**Comment by cthulhuplus** [comment]
Reviewed the SLA document with Jenn

**Comment by cthulhuplus** [comment]
The topics we covered were;
Logs and where and how to find them
"On-call" rotation and when it's appropriate to follow
Hours of Operations/Support
Creating and logging Incidents, both Security and Availability
User communication/support, ft. a real Issue from our backlog (which Tif picked up on!)
Leveraging the CMS Cloud Support and Web Help Desks
The scenarios we worked through were:
You're having issues with your own PR (On-call no necessary, logs can be found in CloudWatch, Splunk, or on the Test Instance)
Prod is down! (Hours of operations, Incident report, contacting a specialist, and the process for running an off schedule deploy to Prod to patch Prod)
Third Party Vendor leaks our pipeline creds (Security incident, contact CMS Security Help Desk, documenting Security incidents and history)
User support via Email to the shared email box (Creating an Issue to address a bug/Checking for a known bug/potentially reprioritizing a known bug based on user feedback)
Bill is unavailable and CircleCI/Pipeline Tool is acting up (Contacting CMS Help Desk, creating an Incident since a major tool in our pipeline is unusable, manually running builds from the command line)
