### ISSUE TITLE
Create a TOC or index for topics in user research findings

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3078]
In the wiki, Create a TOC or index for topics in user research findings so that we can easily see what topics have been studied before and review them as needed, or review a history of the project. 

Note to self - you made a google doc for this a while back 

### This task is done when...
 - [x] Topics in the user research findings section of the wiki are indexed in some way

**Comment by beparticular** [comment]
TOC is created
https://github.com/CMSgov/eAPD/wiki/User-research-findings

@akuas do you want to take a look at the structure and formatting and see how this looks. Let me know any feedback you have about the updated structure of this page on research findings.

**Comment by akuas** [comment]
@beparticular Thanks Jenn, I will take a look now.

**Comment by akuas** [comment]
The format is great. I'm not sure if it was like this before but I especially l liked that you can skim through the research topics and that the most recent session is first. But, since there is a lot of content on this page, one has to scroll a lot. I would suggest we separate the research sessions with [toggles/accordions](https://gist.github.com/orta/057eab0832773aa299a6ebd39187ab06).

**Comment by akuas** [comment]
I see that the links jump you to the part of the page that focuses on the particular research session. That works.
