### ISSUE TITLE
[QA] Share QA steps to verify a ticket

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3124]
To increase team understanding, it would help if the team/dev team/tech lead understood the steps that go into verifying a ticket.

Tiffany would like Amanda, to take note of the steps she takes to verify the next 2-3 tickets she works on. Write them down in a list and then, if necessary please give a sentence or 2 explaining the step.

### This task is done when...
 - [ ] QA has shared the steps it takes to verify a ticket

**Comment by eStar386** [comment]
@Tif In slack you stated, it is my choice of 1-1, team _brown bag_ or a written request this differs from what was discussed. Please confirm this is still informal. Or as requested above ,a written list of my steps taken on each ticket. Please see the [test cases] (https://drive.google.com/drive/folders/1C2czaMJdC3VbutefcItECOx42vvRzr9z?usp=sharing) previously created that highlight the quote below.

> Tiffany would like Amanda, to take note of the steps she takes to verify the next 2-3 tickets she works on. Write them down in a list and then, if necessary please give a sentence or 2 explaining the step. Also some of the test cases containing test notes and are designed to be implemented by any user technical or not. 
 
If I am misunderstanding the request please correct me? 

In the meantime, please see the [QA Roadmap] (https://drive.google.com/file/d/1kkQCbDt14U5xfy7aQQib2tjMYC64iLwx/view?usp=sharing) for a high-level overview because each test case verifies the presence of functional or accessibility criteria defined in the wiki or PR.

**Comment by thetif** [comment]
I think this is a very good start.

> Testing – bolded because all the changes are relatively new
> Purpose: Ensuring the application meets both software requirements and user needs as defined in the wiki.
> Criteria for a Passing Issue, they meet all of the standards listed below.
> QA Steps:
> Reviewing the PR: Ensuring that code relates to the functionality being changed. The scope shouldn’t include other functionality for documentation purposes of the codebase. 
> Accessibility Testing on each component wave, screen reader, and text scaling. 
> Functional testing - ensuring the application meets both software requirements and user needs. 
> Failing Issues from QA proceed return to In Progress: Any direct functional or accessibility issue 
> Passing Issue: Include testing steps in PR  (unless it’s a bug because it’s in the Zenhub Issue).  Updates test scripts in Google Drive, updates pipeline Ready for Review and reviewers Product and Design(when applicable). 

Can you elaborate a little on Reviewing a PR? What is involved in the review? Do you review the code? Are you just reading the PR itself so that you are understanding what it's addressing?

For Accessibility Testing, do you run wave in one browser? All browsers? Which screen reader are you using? Are you using Mac Voice over? Do you test on Parallels too to see if it's working in Windows too?

When testing functionality, is that where you are writing test plans and recording the results of those tests? Is this where it would help to have a test case tool? I was looking into it and saw some that tie in with github, which would be nice.

**Comment by eStar386** [comment]
@thetif - The pieces you have highlighted from the Workflow document have existed for some time. Are you requesting that I update the aforementioned document with answers to these questions as well because I demoed/reviewed it two months ago with the team (in slack/parking lot) and Jerome separately. In addition, the test cases are the test steps that I take. As stated , I am not trying to created alot of test cases but I am trying to have test cases for test automation also mentioned in the aforementioned document.  Please let me know if you want steps to verify a ticket or  updated workflow documentation.

**Comment by eStar386** [comment]
@thetif Please provide feedback on the information provided. Do you have understanding of the process with the notes and meeting on May 25,2021 for QA workflow. Does the notes provided in zenhub/the test case documentation meet the expectations? Also, per the standup yesterday, the result was the FIFO of the QA Pipeline?

**Comment by thetif** [comment]
@eStar386 I think we can address the rest of this ticket next week at the QA Workflow and Roadmap Part 2 meeting. I think instead of saying FIFO because it's jargony, I think we should say, devs will add tickets to the bottom of the QA pipeline and QA should prioritize testing from the top down in the QA pipeline.
