### ISSUE TITLE
[Bug] Unable to view export view and other data related to the FFY when the FFY is unchecked

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3136]
**When FFY is not selected, the app breaks wherever FFY data is collected or viewed i.e. Unable to complete private contractor costs with this issue. Also, the export view breaks entirely and users are not able to view or print this data.-**

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [ ] Usability

**Steps to reproduce-**

1. Uncheck all federal fiscal years options
2. View state costs, private contractor and budget and ffp to see the missing data when ffy is not selected. Other funding is also broken as a result.
3. View the export view when ffy is not selected.

**Role Affected-**
- [ ] All

**Browser-**
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
- Users should still be able to view the export view even when the ffy is not selected
- Pages should not break when the ffy is not selected. This might disorient the user.

**Related user story/bug-** (if applicable)
- Related to [#3041](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3041)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

---

**Comment by beparticular** [comment]
Added the design tag as we'll need to think about what the right experience should be when all FFYs are unchecked.

**Comment by beparticular** [comment]
Per convo with dev, let's explore keeping folks from unchecking all FFYs as the first option to addressing this issue. 

@akuas can you use the modal design for unchecking a FFY and write up some text for what it should say if it's the last FFY that is checked, to let folks know they have to have at least one FFY checked? 
#2996 is open to work on the modal for unchecking a FFY so these are linked issues in the dependencies above. #2996 doesn't block design work, but would block dev work I believe.

**Comment by akuas** [comment]
This video displays how the app breaks especially in the budgets section when the ffy is not selected
https://user-images.githubusercontent.com/57009131/118854790-1071b700-b8a3-11eb-96a7-7a4fd501acf6.mov

**Comment by akuas** [comment]
This video displays how the export view looks when the ffy is not selected.
https://user-images.githubusercontent.com/57009131/118855150-79f1c580-b8a3-11eb-8013-3ab7923ecafb.mov

**Comment by beparticular** [comment]
@akuas @CSwartzHMA any suggestions to improve this language? 

![FFYdeleteall.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/f28d1e8e-87e0-4056-a386-6df872615864)

**Comment by CSwartzHMA** [comment]
Should the Title be "FFY is required"? I want to be sure I am clear. Are there two separate alerts? One to say that unchecking removes all APD info, which is triggered by the removal of the check for any FFY, and then also this one if the last or only FFY is unchecked? But if there is only one, you get only this message? If this is the case, and we need to address both risks in the same alert, I like the direction Akua is going, but I think we could reuse the language about lost data from the other alert for consistency. Maybe just a slight change: "Unchecking an FFY will result in the loss of any activity and budget information previously entered for this FFY. At least one FFY must be selected to continue with your APD."

**Comment by akuas** [comment]
Thanks Caryn, I like the idea of saying that the FFY is required but we cant require that field because that would mean it would be tied to a validation. Yes, from my understanding, there will be two alerts associated with the FFY; one when you are simply unchecking a FFY to indicate that data would be lost and the other, sort of stating that you might not be able to do all the functions (view budget data) without a FFY selected. I like your copy. But, I wonder, in general, if users are really going to understand the difference between the two modals for the FFY. Im also thinking now if we need two modals or just one modal to warn against deleting all the FFY.

**Comment by beparticular** [comment]
Proposed Solution: would not show the modal that exists now when the last FFY is being unchecked. We would only show  one modal or one alert with different language that would prevent someone from deleting the last option.

Consider using red text inline validation as a solution. 
Or potentially the alert in the design system. 

Language for validation could be. 
"At least one FFY must be selected to continue with your APD."

I'll do a quick mock up of a couple of options.

**Comment by beparticular** [comment]
@CSwartzHMA @akuas 
Here are some new ideas for this page. 

I think to reduce confusion, the best way to handle this is to still allow a user to delete the last FFY. 
We will still show the current FFY Delete? modal when they do. 

If someone deletes all their FFY, we'll put up an alert that they need to add one to continue. This won't keep them from moving through the APD due to our validation limitations at this time, but it will at least let them know something needs to be fixed. I'm unsure if this could persist as they move through the app and come back or if it would go away when they move away from the page, so we'll need to check with dev on that. 

Figma Link has two options for the alert. One is an alert box, one is inline validation style. Let me know what you think. 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3751%3A27887

**Comment by CSwartzHMA** [comment]
@beparticular I think this approach sounds good. I like the option with the red box, rather than just the text.

**Comment by thetif** [comment]
1. Header level - put the error in the header panel and change the color to red to alert the user that there is an issue; include a link back to the FFY page

![Screen Shot 2021-06-09 at 4.31.57 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/8d1bb737-dd24-4c69-8ed2-643672b47e38)

2. Pop up an error on all pages

3. Put the error message inside the pages and show it instead of the functionality that it breaks (e.g. budget tables)

**Comment by beparticular** [comment]
@thetif and @akuas please work together on capturing potential solutions we discussed in design sync in the dev ticket
