### ISSUE TITLE
Heartbeat Check before showing the login screen

### ISSUE THREAD

**Issue by knollfear** [CMSgov/eAPD#3223]
As a user when the backend is down the current message I see is "Invalid username or password" because the login check fails.  This is not the most helpful message because it misleads me about the cause of my problems. We should check that our API and Okta are up before displaying the login screen so that the user will have a better understanding of they they cannot log in. Check that the API is up using the /heartbeat endpoint. Check that Okta is up using the web/src/util/auth.js - renewToken and add error handling to fail if the error is a 500. 

**mockup**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3996%3A29116

### This task is done when...

- [ ] a check to the API healtcheck endpoint is preformed and is successful before showing the login screen
- [ ] a check to Okta is performed and is successful before showing the login screen

**Comment by jeromeleecms** [comment]
"The eAPD system is down, try again later." <- please use this language; also use this for the login error for #3232 @akuas

**Comment by beparticular** [comment]
@knollfear here is the Figma link for what the alert should look like. 
It's ok to use this here instead of the general validation style we'd use for a pw error, since it's a bigger deal. 

This will suffice for getting this out now, and then if we need to revisit the design or language in #3236 we can then. Thx! 

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3996%3A29116
