### ISSUE TITLE
[Bug] Revoking a user's access is causing them to disappear and not show in the Inactive tab

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#3238]
**Description-**

**Type of Bug-**

- [ ] Accessibility
- [x] Functional
- [ ] Usability
- [ ] API
- [x] Regression

**Steps to reproduce-**

1. Login with any account that has state admin access
2. Navigate to State Admin dashboard
3. Revoke a user from the "Active" tab
4. Switch to "Inactive" tab

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [x] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [x] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
* Revoked users should immediately appear in the inactive tab

**Actual results-**
* Revoked users are not appearing in the inactive tab when revoked

**Logs or error output/Screenshot/Video-** (at least 1 of these)
https://images.zenhubusercontent.com/113234315/ad82383b-d7f2-4a7f-865d-b42bd78c21cb/screen_recording_2021_07_01_at_12_32_27_pm.mov

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by thetif** [comment]
I am also not seeing someone who I just requested on the pending list.

**Comment by thetif** [comment]
This might be a permissions error because I can see them when I log as fedadmin:

![Screen Shot 2021-07-02 at 12.50.15 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/66d90952-a4ea-477d-85f9-d063fee80eec)
![Screen Shot 2021-07-02 at 12.50.54 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/0238f563-befc-4919-8808-3ea9f20fb538)

but not when I log in as em@il.com:
![Screen Shot 2021-07-02 at 12.52.17 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/a2cd2a7a-955e-4e30-887f-dd31707c802c)
![Screen Shot 2021-07-02 at 12.52.25 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/37c0167e-ffb5-49a7-89a0-5ba417ffb4ce)
