### ISSUE TITLE
[Design Issue] State Admin approval workflow

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3263]
We need a way for Federal Admin's to upload authorization letters that we receive from the states. We need some kind of form that at least takes in the approved user's email, the state, the approving authority, and allows the user to upload the file from the state.

Federal Admin's also need to have some reference to these letters when they are approving access for State Admins. We also need a way for Federal Admin's to remove these letters.

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [ ] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by akuas** [comment]
Hello @CSwartzHMA , what sorts of information is provided in the state admin letter from fed admin?

**Comment by akuas** [comment]
@thetif Besides the ability to upload the letter, how might the fed admin be different from the state admin?

**Comment by CSwartzHMA** [comment]
@akuas the form is [here](https://docs.google.com/document/d/1ExjhwyLivhmdkcFOa_7L81Bzsthe_L9MFaUC86lxJZY/edit?usp=sharing), but we can make changes to the form, if we need to.

**Comment by akuas** [comment]
@CSwartzHMA Thanks!

**Comment by akuas** [comment]
- Need to keep the state admin delegation separate from the fed admin panel because it could get confusing and they might not just request states
- We get emails requesting a user to be a state admin and then we load into requests. It is basically data entry for the state admin
- We can automate in once you put in the system, when they try to login, we can give a approval alert or address whenever you get there. The alert could be a side by side comparison user profile of the state admin input by the federal admin and the user profile of the state user logging in for the first time.
- The ability to upload a list of authorized users is a separate piece from the list of state admin users
- There is no manually entry for the state staff. State admin simply approve them with no oversight. How do we get the initial list of state admin populated?
- Have the form, how do we referebnce and document it and how do we tie the two
- Federal admin pick state admin and upload the delegation letter.
- We are already getting delegating emails but dont have EUA access, but we can store it in the system, verify or add access. Fed admin confirms that by first selecting the edit role button.
- Only federal admin can assign state admin and other federal admin. Federal admin can revoke state admin as well.
- System can can see every user like a fed admin
- As a first step we can list all authorized users with the document as free text, when there is a match, a modal pops up saying the a user is linked to a user listed in the list of authorized users. From there, state users can approve a state admin.
- We could simplify the work flow by having more job codes associated to a user's role in eAPD i.e. eAPD-state-admin for state admin.
- Design wise, we need the form and the ability to upload the delegation letter. Can have a structured from we can extract from later.
- Aging report:30-60 days left on eAPD
- We could scrap the tabs if we feel it doesn't work
- Ty's implementation would be the interim solution. We would then transition to an audit style where federal admin select state admin and then we approve. Finally, the ideal state would be an automated database query.

**Comment by akuas** [comment]
In Jerome's [State Admin Workflow](https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1626296287019/8f353a880e7747d50fe189ca42618f0f051dbb15?sender=2cde9195-7f3a-4097-85e3-c63a2792ab1b) there are two workflows. This is the [design ](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4203%3A28993)for "Adding a state admin to the "Authorized State Admin" list". There are a few things I wanted to revise with this design like demonstrating how a federal admin would add another federal admin. I think for that we can have a similar design to the state switch; fed admin would select what role they are delegating and there would be branching based on whether they select state admin or federal admin.

The second workflow "Authorizing eAPD users for state admin access" is still a work in progress. I am going to figure out if there needs to be any action from the eAPD user as they login to indicate that they want to be elevated to state admin status.

**Comment by akuas** [comment]
The State Admin Approval Workflow begins [here](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4203%3A28993). 
I will add an explanation on the design shortly after design sync.

**Comment by beparticular** [comment]
@thetif ready for dev. summary is in Figma
Summary is annotated in Figma 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4678%3A30798

**Comment by thetif** [comment]
created several dev tasks
