### ISSUE TITLE
[Bug] 401 error when trying to login as sysadmin

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3266]
**Description-**
Logging in as sysadmin locally or in PRs turns 401 when attempting to hit the /me endpoint.

**Type of Bug-**

- [ ] Accessibility
- [X] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. login as sysadmin
2. see 401 error on /me endpoint

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [X] System Admin

**Environment-**

- [X] Local
- [X] PRs
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
Should be presented with the option of selecting from all of the states or federal

**Actual results-**
The /me endpoint returns a 401 error

**Related user story/bug-** (if applicable)
#2581

**Logs or error output/Screenshot/Video-** (at least 1 of these)
![Screen Shot 2021-07-09 at 5.31.09 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/0eeabcad-de12-4d47-89c1-ff2d784f7d3f)

**Comment by knollfear** [comment]
In researching this it seems that the JWT for the sys admin has grown to about 24KB, exceeding the RFC limit of 4096B by a factor of 6.  Since the 4096 limit is part of the browser specification I don't think we are going to get past it.  I think the best solution is going to be to remove the affiliations and permissions portion of the JWT.  Alternatively, we could use bitwise orring to reduce the payload size of any affiliation to just a single integer.  I think this is probably a lot more work than makes sense though.  Other tickets will include this work, and when they are completed this ticket can probably get closed out.

**Comment by thetif** [comment]
resolved in #3264
