### ISSUE TITLE
[Design Issue] Add annual/update fields to the create new APD screen

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3320]
For the next round of testing and possible inclusion in initial MES Expansion implementation, let's go ahead and add an option to choose annual or update on the Create new APD screen. Even if we're not branching off of this yet, it would be good to go ahead and let users mark this, as they are expecting the option when they create a new APD. 

### This task is done when…

- [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by akuas** [comment]
Do as needed APD updates have the same duration as an annual update?; are the funding requests typically used for a whole federal fiscal year or do states sometimes request funding for the current year to last them to the end of the fiscal year?
@jeromeleecms @beparticular

**Comment by jeromeleecms** [comment]
Per 45 CFR 95.610, there are three types of APD-Updates for MMIS and E&E: An Annual APD, an As needed APD, and OAPDU. Each are defined by a specific need -- though it is possible for an As Needed APD to serve as an Annual APD (and vice versa). HITECH regs cover updates in 42 CFR 495.338 (though no OAPD exists in this context).

In regards to your "duration" question, funding requests are stated by Federal Fiscal Year (FFY). States can request current year + two years of funding (though the annual submission is still required). If a state has previously approved funding for their particular MES area, they could request a change of funding (increase/decrease) to a particular FFY in their APD, but collectively (CMS and State) would still have to keep track of any other funding that was approved (that's why the master MDBT becomes much more critical as we expand to other MES areas) and adjust any FFY(s) identified in the APD accordingly.

If you want to run through scenarios, we can also discuss during parking lot.

**Comment by akuas** [comment]
Below is the designs for update in the Create a New APD. I am going to read the reg again to fully understand which updates are available for each APD type and add that logic to the designs @jeromeleecms 
[Create a New APD with APD update](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4799%3A31314)
[Create a New APD with APD update (help drawer expanded)](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4800%3A31531)
@beparticular I think we could have the update as a separate research topic. From the MES expansion 1 research, it seemed that users were quite concerned about being able to populate information from previous APDs into the new APD update they are creating. So, I think if we test the update, we don't necessarily need to test branching now, but it would be helpful to allow users to link the update they are creating to an existing APD. I could come up with rough design for that soon.

**Comment by akuas** [comment]
@jeromeleecms Are there currently definitions for each business area or does MITA have definitions for their business areas we could rework?

**Comment by beparticular** [comment]
This ticket is as done as it needs to be before the next round of testing, or until we get closer to implementation of the MES pieces. 
We will remember that this exists, through #3319
