### ISSUE TITLE
[Feature] Update Active Users tab

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3418]
**Description and related issues -**
The Active user tab is pretty much the same, but the Edit Role button should only show up for State Admins and will be used to demote them to State Staff. The text should be kept as close to as it is now as possible and if there are content questions, please ask Jenn

-----

Every State Admin user should have an Edit Role button next to it. Clicking the Edit Admin button should open the Edit Role modal. Clicking Cancel on the modal should only close the modal. Clicking the Save button on the confirmation modal should change the user's role to State Staff and close the modal. The user's role should be changed to State Staff in the table

**Mockups or link to Figma**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5386%3A33951

### This task is done when…

- [ ] only State Admin users should have an Edit Role button
- [ ] clicking the Edit Role button should open the Edit Role modal
- [ ] clicking the Cancel link should close the modal
- [ ] clicking the Save button should update the user role and close the modal
- [ ] identify 508 considerations and/or recommendations

**Comment by jeromeleecms** [comment]
@Tbolt Based on some conversations with @CSwartzHMA, we had decided that state admins who expired would have their accounts deactivated and the new state admins would be able to regrant them access at the state level (instead of the Fed Admin making that decision). We may have to put some additional processes in place to make sure that state is notified to ensure any expiring state admins who need to keep their access to the state's portion of the system is maintained.
