### ISSUE TITLE
[Design Issue] Make Yes/No checkbox fields consistent across the application 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3487]
We've determined that we want to change all Yes/No checkbox fields to Yes as the first option, regardless of which answer expands to show other fields. 

We also sometimes default a selection in these fields. We have determined that we will remove default selections and want folks to make their own decision. 

### This task is done when…
- [ ] Remove any default selected options 
- [x] Determine all of the places in the system where No is currently the first option and list them here 
- [X] Determine all of the places in the system where a selection is made by default and list it here (KP and Private Contractor) 
- [x] Change the designs in Figma where No is the first option
- [ ] Change the designs in Figma where a selection is made by default based on our decision to show default not selected states

**Comment by akuas** [comment]
[Key State Personnel: Default State](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5383%3A34045)
[Private Contractor Costs : Default State](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5582%3A37983)
This addresses the move away from pre-selecting fields for users. Of course, FFP is an exception because the system would break if unselected.
When implementing this, we just have to make sure if 'yes' is selected and expanded, the contents underneath 'yes' is properly spaced out from the 'no' selection, so that it is clear what the branched content is referring to. Also, as we talked about in last week's design sync, if you enter information for 'yes,' then select 'no' and return to the 'yes' selection, the branched content under 'yes' should still be there.

**Comment by beparticular** [comment]
@akuas @jeromeleecms I think we did determine in another ticket how the FFP would function so we don't need to worry about that here.

**Comment by beparticular** [comment]
@jeromeleecms the designs are all updated, and the instructions for dev are pretty simple moving forward. Please read the following and take a look at the designs and see if there is anything specific to the Yes/No that you see differently than what is outlined here for dev. 

For dev: 
There are two instances of Yes/No in the system where we need to make updates. 
This is in Key State Personnel and in Private Contractor costs. 

Each question in these sections with a Yes/No answer needs to be in the order Yes/No, and no pre-selected choice should be made. The design for the answer that expands needs to match the CMS design system. 

As we talked about in last week's design sync, if you enter information for 'yes,' then select 'no' and return to the 'yes' selection, the branched content under 'yes' should still be there just as it is now.

**Comment by jeromeleecms** [comment]
@beparticular Was the key personnel design supposed to include a view when Yes is selected? I see that in the contractor view where "Yes" is selected and the validation for the expanded fields are included.

**Comment by akuas** [comment]
@jeromeleecms I was mainly focusing on the default/blank state for this ticket, but I have added the expanded costs when ['yes' is selected](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6011%3A38931) for key state personnel now.
