### ISSUE TITLE
[Feature] Update Key State Personnel

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3491]
**Description and related issues -**

Hide alert message for now, it will be addressed further in #3348

---

Display description from inside the form above the Add Primary Contact button
"Personnel listed in this section must be assigned to APD by name, role, time commitment, and cost, where applicable. Add at least one point of contact (key state personnel)." 
Only necessary on the Primary APD Point of Contact
![Screen Shot 2021-12-07 at 3.15.35 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/2398e2d2-f60a-4c87-9f8b-eab1f77fb1bc)

Once Primary POC is added, then it should look like this
![Screen Shot 2021-12-07 at 3.16.20 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/ba203885-0de8-49b3-9481-c103e07ab5b5)

---

Add in-line validation to Key State Personnel form. The validation should appear after the user hits the Add (previously Done) button. If there are validation errors, the errors should display, nothing should be saved, and it should stay on the form until the errors are fixed.
![Screen Shot 2021-09-27 at 2.41.20 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/ac3b35f8-a4d6-4216-b436-3787c269bb11)

---

Update the view of added Primary APD Point of Contact
![Screen Shot 2021-09-27 at 2.32.21 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/518f0c96-3b01-4e1f-9494-c9bc5c892df9)

---

Update the view of added Addition Key Personnel
![Screen Shot 2021-09-27 at 2.37.25 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/7adae0c4-7f56-41bf-b559-721f5eac1371)

### This task is done when…
- [x] hide alert message when list is empty
- [x] update description at the top of the form
- [x] add in-line validation
- [x] update review to match Figma

**Comment by akuas** [comment]
@tbolt @thetif @NAretakis for awareness
The path we ended up with is as follows:
1. User hits the Add Key Personnel to add it to their APD
2. They then fill out the fields. 
 -  They can either fill all the required fields and select the "done" button. The done button would save their information and submit it.
 -  They can fill out some of the fields and select the "done" button. The "done" button will try to save, realize that the form is invalid and trigger inline validations for the unanswered fields. During that trigger, the done button will be disabled until the user fills out all the necessary fields and all the inline validations are resolved. They can then select the now enabled done button to submit and save.
  - They could also select the "cancel" button to exit the subform and delete their entry. When they select "cancel" while editing the form a 2nd time, the cancel button will serve as an "undo" button and revert the form to the previous saved entry/state.
3. The inline validations will not appear in the admin check because the subform has to be valid (all required fields are entered or a subform is cancelled) before one can leave the form. Primary APD POC, as a whole can be in the admin check because an APD needs one but the individual fields within it (the subform) dont need to be validated in the admin check.
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6931%3A49066

**Comment by thetif** [comment]
replaced by #3867
