### ISSUE TITLE
[Design Issue] Design grouping of required fields in help drawer

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3534]
Consider the organization of the fields listed in the help drawer that need to be completed once the error check has been run. Potentially that would include grouping the fields per page. 

We need to consider this interaction when deciding how these field should be grouped: 
These designs should also show what happens when a field is no longer empty, and what happens when the field returns from a not empty to empty state. For instance, someone starts to fill out a field, like regular inline validation the inline validation and the help drawer indication would disappear. If they delete all the information out of a field, it would reappear. This would be a change from when we discussed the potential of calling the field "complete" once someone exists the field. 

### This task is done when…

- [x] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [x] designs are approved by product

**Comment by akuas** [comment]
Below are the designs for the [required fields grouping](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6395%3A39506).

**Comment by akuas** [comment]
Design decisions (subject to change of course)
1. Fields are grouped by pages but can be separated out into fields when it moves into the recently completed section.
2. The recently completed section will store 5 of the most recent work completed. I think we don't need to list much to minimize the visual density of the help drawer and also because I doubt that section would have much use. 
3. The to do section of the help drawer is organized sequentially as they appear in the side nav but the recently completed is organized chronologically, meaning the 1st on the list would be the most recent.
3. Out of the scope of this ticket: There will be the ability to stop the admin check, but also I am recommending the ability to collapse the admin check to view only what folks are working on now and what is next to complete.
4. If a user undos work in a recently complete field, that field moves back up to do. 
5. I don't think we need to display fields or pages in the recently completed that do not have a validation associated with it (in order words "optional fields"). Im not sure if that would be confusing to users though.
6. If a field is no longer empty, we can almost instantly update the tally in the help drawer and move the field/page down to recently completed after they exit a field, not once they start typing.

**Comment by akuas** [comment]
[Field Grouping Designs](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6395%3A39506)
### Design decisions (updated after design sync)
1. Fields are grouped by pages and all the fields within a page must be completed to move the page accordion down to recently completed
2. The name of the fields and subsequent help text would have a strike through them when they complete the field. The tally would also decrease to indicate that work has been completed.
3. The collapse button displays the help drawer in its abridged version. The collapse/ expand buttons would exist for all help drawer screens except the help drawer indicated that they completed all required fields and can return to Export and Submit. The "success" help drawer would have the 'close' button instead.
4. The 'Recently Completed' section will store 5 of the most recent work completed, including work that was completed before the admin check was initiated. I think we don't need to list much to minimize the visual density of the help drawer and also because I doubt that section would have much use.
5. I don't think we need to display fields or pages in the recently completed that do not have a validation associated with it (in order words "optional fields"). Im not sure if that would be confusing to users though.
6. The 'To Do' section of the help drawer is organized sequentially as they appear in the side nav, but the recently completed is organized chronologically, meaning the 1st on the list would be the most recent.
7. Out of the scope of this ticket, reflected in #3536: There will be the ability to stop the admin check, but also I am recommending the ability to collapse the admin check to view only what folks are working on now and what is next to complete.
8. If a user undos work in a recently complete section, that page moves back up to the "to do section" and the tally of tasks increases.
9. Future consideration: If they undo a field after completing the admin check, the help text in the export and submit page for the admin check would indicate that they need to complete it before exporting a final version.
10. If a field is no longer empty, we can almost instantly update the tally in the help drawer and move the field/page down to recently completed **after they exit a field**, not once they start typing.
11. We will be directing users to the page in the admin check not to unanswered fields within the page. Allowing page jumping through unanswered fields is something we can revisit after conducting a usability study on our current implementation of the admin check, but I think with the inline validation, folks should not struggle too much to find which fields to complete.

**Comment by akuas** [comment]
@jeromeleecms Can you please take a look at this ticket?

**Comment by akuas** [comment]
@NAretakis I added you as an assignee for visibility or just in case you review this ticket. Thank you.

**Comment by NAretakis** [comment]
Yup yup, approved. Let's make it happen, thanks @akuas

**Comment by akuas** [comment]
@NAretakis Thanks! @thetif This ticket is ready for dev.

**Comment by akuas** [comment]
@thetif Unless there are additional considerations to take into account, I think this design ticket is ready to close.

**Comment by thetif** [comment]
created dev ticket #3676

**Comment by akuas** [comment]
Additional dev work not reflected in design decisions post.
1. Update help text for admin check
2. Update help text for admin check on export and submit page and on the actual admin check
3. Develop tally animation for incomplete required fields that moves the numbers downward when decreasing in total and upward when increasing
@thetif
