### ISSUE TITLE
[Feature] Generate a filename for the certification letters when they are added

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3572]
**Description and related issues -**
When state certification letters are viewed or downloaded, they have a generic name. Update the code to generate a name using the format (Name)-(State)-(FFY).pdf

### This task is done when…

- [ ] the pdfs have a name matching the format (Lastname)-(Firstname)-(State)-(FFY).pdf when they are viewed or downloaded

**Comment by tbolt** [comment]
@thetif Adding a quick note on this so I don't forget:
I am generating the filename on the fly when a file is requested/downloaded. We currently don't persist any information about the document (on our end) other than the fileId(which we save as a fully qualified url). Do we want to do a migration and start saving this metadata in this ticket?

**Comment by tbolt** [comment]
Note on this ticket. We don't collect "First Name" and "Last Name" separately but rather via a single "Full Name" field. So in cases where the first name or last name is two words we can't reverse the order. I propose we use the format- 
(Name)-(State)-(FFY).pdf otherwise we can live with the name just being reversed order or update the form to collect first name and last name separately
