### ISSUE TITLE
[Design Issue] Add "draft" tag and version number to export view

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3651]
Based on criteria laid out in #3507 for the lock and submit feature:

At any time, a user should be able to export an existing APD before the admin check is complete. Each export should include:
- version numbers 
- designation that it is a draft
- every export would increase the point number (e.g. "export 0.1" or "export 0.2")

### This task is done when...

- [x]  designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

**Comment by akuas** [comment]
The draft tag and version number will live on the cover page. I don't think we need to mention it on each page on the header. Also, we may need to rework the terms, draft version and submitted/final version. Draft version seems clear enough but if we call the locked down export the submitted version, it can get confusing because users cannot submit to CMS directly in the system and it doesn't accurately represent that that type of export is. Also, colloquially, I have been calling the locked APD export the final version but since users can unlock an APD, calling that export the final version is also misleading.

**Comment by akuas** [comment]
Below are the current designs for the the cover page including the status and version number. The copy and the option of adding that "flag" design for the status and funding source is subject to change. 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7020%3A44566

**Comment by akuas** [comment]
@thetif I added the draft tag designation and version number to the cover page. Please let me know what you think about this. I know dev will be implementing version numbers much later, so feel free to reach out if something crops up from its implementation.

**Comment by akuas** [comment]
@NAretakis This ticket is now ready for review.

**Comment by NAretakis** [comment]
I think I already gave this a thumbs up via #3579, but if not, this still looks good to me.

**Comment by thetif** [comment]
It looks good @akuas great work!

**Comment by thetif** [comment]
created ticket #3723 and #3725
