### ISSUE TITLE
[Design issue] Design MVP for Create APD page

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3687]
The Create APD Page should be redesigned to allow for choosing MMIS iAPD or HITCH as a funding source. There is a more robust version of this here in Figma that contains all APD types: 
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=93%3A5981

We need something simpler for when we add only MMIS iAPD. 

Don't forget #3319, how/when/will people edit this information provided in the create new APD section, or somewhere in the app. 

### This task is done when...

- [x]  designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [x] a list of changes to be made if this is improving an existing feature
---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by beparticular** [comment]
Note - @akuas  is the assignee, but I added myself so we can pair on thinking about the editing process for the information people will add here.

**Comment by akuas** [comment]
Below is the designs for the Create a New APD MVP
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=8903%3A27228

**Comment by akuas** [comment]
@jeromeleecms Can you please take a look at this design? I was especially wondering if the "What type of APD are you creating's copy and options makes sense.

**Comment by akuas** [comment]
Actually, please disregard the previous link I moved the page to the mmis file
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2%3A3237

**Comment by jeromeleecms** [comment]
I can't seem to access the link - are the permissions set to allow me to join anonymously or using my CMS google account?

**Comment by akuas** [comment]
@jeromeleecms Oh right, I have added you, so hopefully you should be able to access the link.

**Comment by akuas** [comment]
@jeromeleecms for the 8th question, Ill defer to @beparticular . But I agree no admin check but Im also thinking the disabled button accompanied with the asterisk should be enough so maybe the inline validation is not needed ?

**Comment by akuas** [comment]
@jeromeleecms @beparticular I updated the designs, so it is ready for review. For the Other Medicaid Business areas, are you saying that the other checked is enough and the text box isnt needed?

**Comment by akuas** [comment]
I think we should keep it as a text box to allow for multiple business areas. I think I want to steer away from the add one component because it seems like a lot of effort for a field that hopefully wouldn't be used too often and combining the business area explanations should still make sense to the reviewer. 
For question 2, I put the unabbreviated term for HITECH IAPD and MMIS IAPD in a tooltip because the text was getting a bit long. We can use the CMS's design system for this. 
For question 4, can you please send me the link for the business areas list, I thought I was updating. it with the new ones.

**Comment by akuas** [comment]
@jeromeleecms @beparticular I made changes to the other medicaid business areas, keeping in mind that the business areas might change. If there is nothing else to edit, I think this ticket is ready to close.

**Comment by akuas** [comment]
**Closing Notes for Dev and for Posterity!**
1. The help text "Complete the fields below to create your APD. Selections with a * cannot be changed after this screen." is our way of informing users that the changes are final but the help text might change pr the asterisk beside the Medicaid Business Areas might be removed when we allow editing after creating the APD. 
2. APD type: Since we only have HITECH IAPD and MMIS IAPD, the funding source and APD type is consolidated, when more options are available we will break the fields up, in the future. The tooltip comes from the CMS design system. We are going to use this component sparingly ion the future to determine a few terms.
3. Medicaid Business Area: The Medicaid MES Certification Repository will direct you to the CMS Certification GitHub: https://cmsgov.github.io/CMCS-DSG-DSS-Certification/  . This list is subject to change so we will need a way to keep it updated.
4. Cancel will direct you back to the dashboard and delete progress of this form.
5. Deciding where we will keep the Create a New APD page after creating the form is out of scope of this ticket, as well as how we will allow the Medicaid Business Area to be edited . However so far, we are leaning towards, putting the business areas in the header next the APD name to be edited.
6. The Create an APD button is disabled until you complete the form.

3.

**Comment by akuas** [comment]
Out of the scope of this ticket: APD name, APD update and business areas can be changed after creating a new APD.

**Comment by akuas** [comment]
@beparticular @jeromeleecms If there are no more changes, I think this ticket is ready to close.

**Comment by beparticular** [comment]
@thetif see the Closing Notes above, edited based on our convos from design sync. let me know if you have any questions!

**Comment by beparticular** [comment]
One last addition - we'd worked out how to handle the HITECH/Biz Areas issue in earlier designs for this feature. I'll add it back to the designs and update the closing notes after sprint planning.

**Comment by akuas** [comment]
I updated the design to reflect that @beparticular @thetif  
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=93%3A5981

**Comment by akuas** [comment]
@mirano-darren @beparticular @jeromeleecms Ive added the designs to include the inline validation messages.
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=93%3A5981

**Comment by akuas** [comment]
Updated Closing Notes as of July 14, 2022 
Final Designs

The help text "Complete the fields below to create your APD. Selections with a * cannot be changed after this screen." is our way of informing users that they cannot change the APD type after they create an APD. APD type is the ONLY field that cannot be edited when we allow that.
APD type: Since we only have HITECH IAPD and MMIS IAPD, the funding source and APD type is consolidated, when more options are available we will break the fields up, in the future. The tooltip comes from the CMS design system. We are going to use this component sparingly ion the future to determine a few terms.
Medicaid Business Area: The Medicaid MES Certification Repository will direct you to the CMS Certification GitHub: https://cmsgov.github.io/CMCS-DSG-DSS-Certification/ . This list is subject to change so we will need a way to keep it updated. Eligibility and Enrollment is removed from the list. We may bring it back when E&E is available. MES Business areas are like meta tags like APD updates, at the moment. For MVP, it will not trigger a change in help text and fields in the same way the Funding Source/APD type field will be. So, the business areas can be changed after creating a new APD.
Cancel will direct you back to the dashboard and delete progress of this form. (this is the same as the subforms)
Deciding where we will keep the Create a New APD page after creating the form is out of scope of this ticket, as well as how we will allow the Medicaid Business Area to be edited . However so far, we are leaning towards, putting the business areas in the header next the APD name to be edited.
The Create an APD button is disabled until you complete the form.
APD Update: The child checkbox only appears if you select yes. Users can select both.
There are no inline validations needed for this page. I think that makes sense to me because it's an isolated page.
@thetif Please let me know if you have questions.

**Comment by beparticular** [comment]
@thetif this is good to go now after we made those few changes we talked about at design sync. please see @akuas 's notes on the comment above and let me know if you have any questions once you start making dev tickets.

**Comment by beparticular** [comment]
#4209 is the dev ticket. Jenn will review the dev ticket to ensure accuracy across the handoff.
