### ISSUE TITLE
Create a way to lock an APD

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3708]
Upon completing an APD, there should be a way to lock it so that it cannot be edited once it is assumed to have been submitted to CMS. This ticket only pertains to locking an APD. Considerations for unlocking an APD are documented in #3730. 

Additionally, those who do not have lock permission will need a separate experience for exporting an APD. They should not see any of the lock functionally. 

The ability to lock an APD could appear:
- on the export and submit screen (after an admin check is performed)
- on the dashboard

Considerations:
- Ability to lock should happen after validation errors are clear
- Admin check serves as trigger that enables ability to lock
- Only an "official submitter" will have permission to lock an APD
- On the backend, we are storing a copy of the last exported APD
- Locking an APD creates a major integer (whole number) version of a saved APD

Once an APD is locked a user should:
- be able to access it from the dashboard
- be able to open a non-editable version
- be able to access the last exported version
- not need to access the export and submit page

### This task is done when...

- [x] corresponding issues are created 
- [x] considerations and/or recommendations are reviewed
- [x] workflow is approved by product
---

**Comment by akuas** [comment]
@aricka-lewis for awareness. I asked about the roles in parking lot because it is relevant to the admin check and lock down and submit. Here is a recap.
State author: write, edit, create draft etc.
State coordinator = state admin: can all of the things state authors can do + activities related to roles and users (view, add, create, edit roles and users)

How it relates to lock down and submit: 
We can make the state admin the official APD submitter and in a way elaborate on their permissions. In other words, state administrator will have the ability to do lock down and submit exclusively.

How it relates to admin check:
We still need to figure out if both state admin and state authors should be allowed to run the admin check or just the state admin.

**Comment by aricka-lewis** [comment]
Ticket has been updated after discussion in design sync today @akuas @jeromeleecms

**Comment by akuas** [comment]
@aricka-lewis Thanks!

**Comment by aricka-lewis** [comment]
Corresponding issues have been created and criteria for locking have been agreed upon.

**Comment by jeromeleecms** [comment]
Are we good to close this out now @aricka-lewis ? The resulting issues seems fine.

**Comment by aricka-lewis** [comment]
Yep, will close now @jeromeleecms
