### ISSUE TITLE
Review Mongo changes in staging

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#3831]
Describe the task here and link or add dependencies to any applicable issues...
Mongo has been implemented in staging. Going to look around and make sure the merge didn't break anything

### This task is done when...

- [ ] staging has been reviewed

**Comment by mirano-darren** [comment]
Some stuff I noticed:
Fed/state admin portal have empty rows in the tables. Not sure if this is intentional or not.
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/75713ad7-16f9-4b19-93ff-0d64f6a3e42d)![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/d6790d26-0034-479f-98a5-3367747b1211)

In the Key State Personnel section of an APD, the text fields are filled out. This could be intentional as well, but the language here confuses me. To me it's not immediately clear what it's trying to say. I think it means that you fill out the Medicaid Director fields, keep them, and re-enter them below. 
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/1ca9c4da-8377-4aa3-aa9f-73e8048cb961)

The lockedout account isn't actually locked out, though someone could've tested unlocking an account
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/13e6b134-67af-4c68-8707-3092ca7e7b52)
it should go to this screen:
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/88ada6db-0319-4cd6-85e4-80e82c11b241)
(also the error icon isn't rendering, however the pic was taken from my personal branch)

**Comment by thetif** [comment]
The state and federal admin portals weren't affected by this change. That's a hold over from users that were created prior to getting their user information from Okta. I could clean it up in the database.

The key state personnel thing is part of the slim mmis thing, I think, where Nick/Jerome was showing what fields would be needed for an MMIS.

You have to manually lock out the user before you get to the account locked page, because it resets to unlocked after 30 minutes - an hour.

I fixed that error icon in this branch that I'm about to push up. Good catch.

**Comment by mirano-darren** [comment]
Sweet! Thanks for the insight. Other than that, the site looked just as expected. Nice work implementing Mongo!
