### ISSUE TITLE
Reorder links on dashboard based on priority of use

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3920]
During lockdown and submit research, all of the participants mentioned the delete action being alarming. This was usually because folks reuse information inside of APDs. 

We should reorder the list of links by usefulness to mitigate concern of accidentally deleting an APD.

### This task is done when...

 - [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
 - [x] 508 considerations and/or recommendations are reviewed
 - [x] designs are shared
 - [x] designs are approved by product

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
I updated the links on the dashboard based on priority of use. Lock is first so that it is a bit easier to find on the dashboard. Keep in mind that this might change with the dashboard redesign. We might decide to hide the delete button in some way to prevent accidental clicking and we will most likely redesign these call to action layout.

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=7643%3A57370

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=7370%3A46497

**Comment by akuas** [comment]
@aricka-lewis can you please review this ticket?

**Comment by akuas** [comment]
Here is the updated link @aricka-lewis 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=7377%3A48735

**Comment by aricka-lewis** [comment]
Looks good, thanks! @akuas

**Comment by akuas** [comment]
@jeromeleecms Can you please review this ticket?

**Comment by beparticular** [comment]
@jeromeleecms I have reviewed and this seems fine. do you have any concerns?

**Comment by jeromeleecms** [comment]
Thanks @beparticular -- this makes sense based on our research sessions. Ready for Dev!

**Comment by thetif** [comment]
created dev ticket #4054
